version: 0.2

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-west-2
    
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g npm@latest
      # Install Terraform
      - curl -O https://releases.hashicorp.com/terraform/0.15.0/terraform_0.15.0_linux_amd64.zip
      - unzip terraform_0.15.0_linux_amd64.zip
      - sudo mv terraform /usr/local/bin/
      - terraform --version
  
  pre_build:
    commands:
      - aws sts get-caller-identity
      

  build:
    commands:
      - npm run build
       # Initialize Terraform
      - echo Building VPC using Terraform 
      - terraform init
      - terraform plan -out=tfplan -input=false
      - terraform apply -input=false tfplan | tee tfoutput.txt
   
  post_build:
    commands:
      - echo "Terraform completed on `date`"
      - echo "Destroying VPC using Terraform"
      #- echo "Scheduling Terraform destroy in 1 hour"
      #- echo "sleep 120; terraform destroy -auto-approve" | at now + 2 minutes
      #- (sleep 120 && terraform destroy -auto-approve) &
      #- terraform destroy -auto-approve
      - VPC_ID=$(grep -A1 "vpc_id" tfoutput.txt | tail -n1 | awk '{print $NF}')
      - echo "Retrieved VPC ID: $VPC_ID"
      - echo "Scheduling Terraform destroy in 2 minutes"
      - sleep 120 && terraform destroy -auto-approve
      
      # - aws events put-rule --name "DestroyTerraformAfter1Hour" --schedule-expression "rate(1 hour)"
      # - aws events put-targets --rule "DestroyTerraformAfter1Hour" --targets "Id"="1","Arn"="arn:aws:lambda:us-west-2:1234567890:function:YourLambdaFunctionName"
  

artifacts:
  files:
    - '**/*'
  name: MyApplication
