version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
  
      - npm install -g npm@latest
      - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip
      - unzip terraform_install.zip -d /usr/bin/
      - chmod +x /usr/bin/terraform
  
    build:
    commands:
      - npm run build
      - terraform init
      - terraform plan
      - terraform apply -auto-approve tfplan
      
artifacts:
  files:
    - '**/*'
  name: MyApplication
