version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
  
      - npm install -g npm@latest

  build:
    commands:
      - npm run build
      
artifacts:
  files:
    - '**/*'
  name: MyApplication
