version: 0.2

env:
  variables:
    AWS_ACCESS_KEY_ID: "AKIAW7522JL6J3BMUGF6"
    AWS_SECRET_ACCESS_KEY: "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"
    
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g npm@latest
      # Install Terraform
      - curl -O https://releases.hashicorp.com/terraform/0.15.0/terraform_0.15.0_linux_amd64.zip
      - unzip terraform_0.15.0_linux_amd64.zip
      - sudo mv terraform /usr/local/bin/
      - terraform --version
  
  pre_build:
    commands:
      - aws sts get-caller-identity

  build:
    commands:
      - npm run build
       # Initialize Terraform
      - echo Building VPC using Terraform 
      - terraform init
      #- terraform plan
      #- terraform apply -auto-approve
      - terraform plan -out=tfplan -input=false
      - terraform apply -input=false tfplan
  
  
  
  post_build:
    commands:
      - echo "Terraform completed on `date`"
      
artifacts:
  files:
    - '**/*'
  name: MyApplication