version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g npm@latest
      # Install Terraform
      - curl -O https://releases.hashicorp.com/terraform/0.15.0/terraform_0.15.0_linux_amd64.zip
      - unzip terraform_0.15.0_linux_amd64.zip
      - sudo mv terraform /usr/local/bin/
      - terraform --version
  
pre_build:
    commands:
      - echo Logging in to AWS ECR
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  
build:
    commands:
      #- npm run build
       # Initialize Terraform
      - echo Building VPC using Terraform
      - cd terraform/vpc  
      - terraform init
      - terraform plan -out=tfplan -input=false
      - terraform apply -input=false tfplan

post_build:
    commands:
      - echo "Terraform completed on `date`"
      
artifacts:
  files:
    - '**/*'
  name: MyApplication