name: Terraform Pipeline

on:
push:
  branches:
    - main

jobs:
terraform:
  runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.7
    
    - - name: Configure AWS credentials
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
run: |
  aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

    - name: Initialize Terraform
      run: terraform init

    - name: Plan infrastructure
      run: terraform plan

    - name: Deploy infrastructure
      run: terraform apply --auto-approve
